version: '3.8'
# WARNING: Replace ADMIN_USERNAME, ADMIN_PASSWORD and JWT_SECRET
# with strong values before deploying to production.

services:
  whatsapp-manager:
    build: .
    env_file:
      - .env
    image: whatsapp-manager:latest
    container_name: whatsapp-manager
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "3000:3000"
      - "${WEBSOCKET_PORT:-3001}:${WEBSOCKET_PORT:-3001}"
    environment:
#      Replace default credentials before using in production
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/whatsapp_manager.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /dev/shm:/dev/shm
    networks:
      - whatsapp-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

  nginx:
    image: nginx:alpine
    container_name: whatsapp-manager-nginx
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    depends_on:
      whatsapp-manager:
        condition: service_healthy
    networks:
      - whatsapp-manager-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7-alpine
    container_name: whatsapp-manager-redis
    restart: ${RESTART_POLICY:-unless-stopped}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-whatsapp123}
    volumes:
      - redis_data:/data
    networks:
      - whatsapp-manager-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

networks:
  whatsapp-manager-network:
    name: whatsapp-manager-network
    driver: bridge

volumes:
  data:
  logs:
  nginx_cache:
  nginx_logs:
  redis_data:
