version: '3.8'

services:
  whatsapp-manager:
    build: .
    image: whatsapp-manager:latest
    container_name: whatsapp-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/whatsapp_manager.db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=whatsapp-manager-secret-key-2024
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - MAX_AUTH_ATTEMPTS=${MAX_AUTH_ATTEMPTS:-5}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - ENABLE_WEBSOCKET=${ENABLE_WEBSOCKET:-true}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-3001}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /dev/shm:/dev/shm
    networks:
      - whatsapp-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

  nginx:
    image: nginx:alpine
    container_name: whatsapp-manager-nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    depends_on:
      whatsapp-manager:
        condition: service_healthy
    networks:
      - whatsapp-manager-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7-alpine
    container_name: whatsapp-manager-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-whatsapp123}
    volumes:
      - redis_data:/data
    networks:
      - whatsapp-manager-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

networks:
  whatsapp-manager-network:
    name: whatsapp-manager-network
    driver: bridge

volumes:
  data:
  logs:
  nginx_cache:
  nginx_logs:
  redis_data:
