module.exports = {
  apps: [
    {
      name: "whatsapp-manager-app",
      script: "server.js",
      cwd: process.cwd(),
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        HOST: "0.0.0.0",
        PUPPETEER_ARGS: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage",
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || "24h",
        ADMIN_USERNAME: process.env.ADMIN_USERNAME,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        MAX_AUTH_ATTEMPTS: process.env.MAX_AUTH_ATTEMPTS || "5",
        DATABASE_PATH: process.env.DATABASE_PATH || "./data/whatsapp_manager.db",
        NEXT_PUBLIC_DOMAIN_NAME: process.env.NEXT_PUBLIC_DOMAIN_NAME,
        NEXT_PUBLIC_WHATSAPP_API_URL: process.env.NEXT_PUBLIC_WHATSAPP_API_URL,
        FRONTEND_URL: process.env.FRONTEND_URL || "http://localhost:3000",
        LOG_LEVEL: process.env.LOG_LEVEL || "debug",
        ENABLE_WEBSOCKET: "false", // تعطيل WebSocket في التطبيق الرئيسي
        WEBSOCKET_PORT: process.env.WEBSOCKET_PORT || "3001",
        NEXT_PUBLIC_WEBSOCKET_URL:
          process.env.NEXT_PUBLIC_WEBSOCKET_URL ||
          `ws://localhost:${process.env.WEBSOCKET_PORT || "3001"}/ws/socket.io`,
      },
      error_file: "logs/app-error.log",
      out_file: "logs/app-out.log",
      log_file: "logs/app-combined.log",
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
      kill_timeout: 5000,
      listen_timeout: 3000,
      wait_ready: true,
    },
    {
      name: "whatsapp-manager-websocket",
      script: "npm",
      args: "run ws:prod",
      cwd: process.cwd(),
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "512M",
      interpreter: "node",
      node_args: "",
      env: {
        NODE_ENV: "production",
        WEBSOCKET_PORT: 3001,
        FRONTEND_URL: process.env.FRONTEND_URL || "http://localhost:3000",
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || "24h",
        LOG_LEVEL: process.env.LOG_LEVEL || "debug",
      },
      error_file: "logs/websocket-error.log",
      out_file: "logs/websocket-out.log",
      log_file: "logs/websocket-combined.log",
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
      kill_timeout: 5000,
      listen_timeout: 3000,
      wait_ready: true,
    },
  ],
}
