name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: cp .env.test .env
      - run: npm ci --ignore-scripts
        env:
          PUPPETEER_SKIP_DOWNLOAD: '1'
      - run: npm run lint
      - run: npm test
